version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    groups:
      bundler-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "bundler"
    directory: "/mustermann-contrib"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    groups:
      bundler-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "bundler"
    directory: "/mustermann"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    groups:
      bundler-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "bundler"
    directory: "/support"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    groups:
      bundler-dependencies:
        patterns:
          - "*"
